name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y libtool pkg-config autoconf automake scons qemu-user-static locales openjdk-17-jdk-headless libffi-dev libssl-dev
        pip install --upgrade buildozer wheel setuptools "cython<3.0.0" virtualenv

    - name: Adjust Buildozer Specification
      run: |
        # Este comando busca automáticamente en tu archivo .spec y corrige las APIs conflictivas
        sed -i 's/^android.minapi =.*/android.minapi = 21/' buildozer.spec
        sed -i 's/^android.api =.*/android.api = 33/' buildozer.spec

    - name: Build with Buildozer
      run: yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MiAppGimnasio
        path: bin/*.apk
