name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK & Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config scons qemu-user-static locales libffi-dev libssl-dev
        # Forzamos la instalación de Cython y dependencias necesarias para el subproceso
        pip install --upgrade "Cython<3.0.0" wheel setuptools virtualenv python-for-android kivy

    - name: Setup Android Build Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-33" "build-tools;33.0.2" "platform-tools"

    - name: Compilar APK con Python-for-Android
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        # Agregamos la bandera --use-setup-py para que no intente crear entornos aislados sin Cython
        p4a apk --private . \
          --package=org.ferpalacios.miappgym \
          --name="Mi App Gym" \
          --version=0.1 \
          --bootstrap=sdl2 \
          --requirements=python3,kivy \
          --arch=arm64-v8a \
          --orientation=portrait \
          --android_api=33 \
          --min-api=21 \
          --ignore-setup-py

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MiAppGimnasio
        path: "*.apk"
